# Generated by Django 4.2.27 on 2026-01-08 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElasticityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elasticity_level', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], max_length=10, unique=True)),
                ('max_extra_hours_week', models.DecimalField(decimal_places=1, default=0, help_text='Máximo de horas extra por semana', max_digits=4)),
                ('max_extra_hours_day', models.DecimalField(decimal_places=1, default=0, help_text='Máximo de horas extra por día', max_digits=3)),
                ('assignment_priority', models.PositiveIntegerField(default=1, help_text='Prioridad al asignar horas extra (mayor = primero)')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Regla de Elasticidad',
                'verbose_name_plural': 'Reglas de Elasticidad',
                'ordering': ['-assignment_priority'],
            },
        ),
        migrations.CreateModel(
            name='PlanningParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único del parámetro', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_type', models.CharField(choices=[('INTEGER', 'Entero'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Booleano'), ('TEXT', 'Texto'), ('TIME', 'Hora')], default='INTEGER', max_length=20)),
                ('value', models.CharField(help_text='Valor del parámetro', max_length=200)),
                ('category', models.CharField(default='GENERAL', help_text='Categoría para agrupar parámetros', max_length=50)),
            ],
            options={
                'verbose_name': 'Parámetro de Planificación',
                'verbose_name_plural': 'Parámetros de Planificación',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ZoneAssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('value_boolean', models.BooleanField(blank=True, help_text='Valor booleano para reglas tipo on/off', null=True)),
                ('value_integer', models.IntegerField(blank=True, help_text='Valor entero para reglas numéricas', null=True)),
                ('value_text', models.CharField(blank=True, help_text='Valor texto para reglas de configuración', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Asignación de Zona',
                'verbose_name_plural': 'Reglas de Asignación de Zona',
            },
        ),
        migrations.CreateModel(
            name='TaskTimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('NONE', 'Sin condición (base)'), ('SUITE', 'Es Suite'), ('VIP', 'Es VIP'), ('RECOUCH_DECLINED', 'Recouch rechazado'), ('STAY_LONG', 'Estancia larga (>5 días)'), ('FIRST_DAY', 'Primer día'), ('LATE_CHECKOUT', 'Checkout tardío'), ('EARLY_CHECKIN', 'Checkin temprano')], default='NONE', help_text='Condición para aplicar esta regla', max_length=30)),
                ('base_minutes', models.PositiveIntegerField(blank=True, help_text='Tiempo base en minutos (si es regla base)', null=True)),
                ('time_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador de tiempo (ej: 1.4 = +40%)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('priority', models.PositiveIntegerField(default=10, help_text='Prioridad de la regla (mayor = se aplica primero)')),
                ('description', models.TextField(blank=True, help_text='Explicación de cuándo y por qué aplica esta regla')),
                ('is_active', models.BooleanField(default=True)),
                ('room_type', models.ForeignKey(blank=True, help_text='Si se especifica, la regla solo aplica a este tipo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='core.roomtype')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_rules', to='core.tasktype')),
            ],
            options={
                'verbose_name': 'Regla de Tiempo',
                'verbose_name_plural': 'Reglas de Tiempo',
                'ordering': ['task_type', '-priority'],
            },
        ),
    ]
