# Generated by Django 4.2.27 on 2026-01-08 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtelImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('imported_by', models.CharField(blank=True, help_text='Usuario que realizó la importación', max_length=100)),
                ('rows_processed', models.PositiveIntegerField(default=0)),
                ('rows_success', models.PositiveIntegerField(default=0)),
                ('rows_error', models.PositiveIntegerField(default=0)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('errors', models.TextField(blank=True, help_text='Lista de errores encontrados durante la importación')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido')], default='PENDING', max_length=20)),
            ],
            options={
                'verbose_name': 'Log de Importación Protel',
                'verbose_name_plural': 'Logs de Importación Protel',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomDailyState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha del estado')),
                ('occupancy_status', models.CharField(choices=[('VACANT', 'Vacante'), ('OCCUPIED', 'Ocupada'), ('CHECKOUT', 'Checkout (salida)'), ('CHECKIN', 'Checkin (llegada)'), ('TURNOVER', 'Turnover (salida + llegada)'), ('OOO', 'Fuera de servicio')], default='VACANT', max_length=20)),
                ('stay_day_number', models.PositiveIntegerField(default=1, help_text='Día de estancia del huésped (1 = primera noche)', validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_checkout_time', models.TimeField(blank=True, help_text='Hora prevista de checkout', null=True)),
                ('expected_checkin_time', models.TimeField(blank=True, help_text='Hora prevista de checkin', null=True)),
                ('day_cleaning_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('DONE', 'Realizado'), ('DECLINED', 'Rechazado por huésped'), ('NOT_REQUIRED', 'No requerido')], default='PENDING', max_length=20)),
                ('night_expected_difficulty', models.CharField(choices=[('NORMAL', 'Normal'), ('HARD', 'Difícil (recouch rechazado)'), ('VERY_HARD', 'Muy difícil')], default='NORMAL', max_length=20)),
                ('is_vip', models.BooleanField(default=False, help_text='¿Es cliente VIP?')),
                ('notes', models.TextField(blank=True, help_text='Notas especiales para este día')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_states', to='core.room')),
            ],
            options={
                'verbose_name': 'Estado Diario de Habitación',
                'verbose_name_plural': 'Estados Diarios de Habitaciones',
                'ordering': ['date', 'room__zone', 'room__order_in_zone'],
                'unique_together': {('date', 'room')},
            },
        ),
        migrations.CreateModel(
            name='RoomDailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_minutes', models.PositiveIntegerField(default=0, help_text='Tiempo estimado en minutos')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignada'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('priority', models.PositiveIntegerField(default=50, help_text='Prioridad 1-100 (menor = más prioritario)')),
                ('notes', models.TextField(blank=True)),
                ('room_daily_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rooms.roomdailystate')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_tasks', to='core.tasktype')),
                ('time_block', models.ForeignKey(help_text='Bloque temporal donde se debe realizar', on_delete=django.db.models.deletion.PROTECT, related_name='room_tasks', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Tarea de Habitación',
                'verbose_name_plural': 'Tareas de Habitaciones',
                'ordering': ['priority', 'task_type__priority'],
            },
        ),
    ]
