# Generated by Django 4.2.27 on 2026-01-08 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(help_text='Código único del empleado', max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('weekly_hours_target', models.DecimalField(decimal_places=1, help_text='Horas semanales objetivo (ej: 35, 24, 20)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(48)])),
                ('elasticity', models.CharField(choices=[('LOW', 'Baja - No estirar horas'), ('MEDIUM', 'Media - Puede hacer ±2h'), ('HIGH', 'Alta - Flexible, puede cubrir huecos')], default='MEDIUM', help_text='Flexibilidad para ajustar horas', max_length=10)),
                ('can_work_night', models.BooleanField(default=False, help_text='¿Puede trabajar en bloque NIGHT?')),
                ('is_active', models.BooleanField(default=True)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('allowed_blocks', models.ManyToManyField(help_text='Bloques donde puede trabajar este empleado', related_name='employees', to='core.timeblock')),
                ('eligible_tasks', models.ManyToManyField(help_text='Tareas que puede realizar este empleado', related_name='eligible_employees', to='core.tasktype')),
                ('fixed_days_off', models.ManyToManyField(blank=True, help_text='Días fijos de descanso. Si vacío, el sistema elige.', related_name='employees_off', to='core.dayofweek')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre del equipo (ej: 'María + Carmen')", max_length=100)),
                ('team_type', models.CharField(choices=[('FIXED', 'Fija - Siempre juntas'), ('PREFERRED', 'Preferida - Juntas por defecto'), ('TEMPORARY', 'Temporal - Solo para esta semana')], default='FIXED', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('members', models.ManyToManyField(related_name='teams', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Equipo/Pareja',
                'verbose_name_plural': 'Equipos/Parejas',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_blocks', models.ManyToManyField(help_text='Bloques temporales donde este rol puede trabajar', related_name='roles', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['display_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('reason', models.CharField(choices=[('VACATION', 'Vacaciones'), ('SICK', 'Baja médica'), ('PERSONAL', 'Asunto personal'), ('TRAINING', 'Formación'), ('OTHER', 'Otro')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailabilities', to='staff.employee')),
            ],
            options={
                'verbose_name': 'Indisponibilidad',
                'verbose_name_plural': 'Indisponibilidades',
                'ordering': ['date_start'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='staff.role'),
        ),
    ]
