# Generated by Django 4.2.27 on 2026-01-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='can_clean_rooms',
            field=models.BooleanField(default=False, help_text='¿Este rol realiza limpieza de habitaciones?'),
        ),
    ]
