# Generated by Django 4.2.27 on 2026-01-08 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Edificio',
                'verbose_name_plural': 'Edificios',
            },
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('iso_weekday', models.PositiveIntegerField(help_text='1=Lunes, 7=Domingo (ISO)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)])),
            ],
            options={
                'verbose_name': 'Día de la Semana',
                'verbose_name_plural': 'Días de la Semana',
                'ordering': ['iso_weekday'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('time_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Multiplicador de tiempo (1.0 = normal, 1.5 = 50% más)', max_digits=3, validators=[django.core.validators.MinValueValidator(0.5), django.core.validators.MaxValueValidator(3.0)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
            },
        ),
        migrations.CreateModel(
            name='TimeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: DAY, EVENING, NIGHT)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del bloque')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición (menor = primero)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bloque Temporal',
                'verbose_name_plural': 'Bloques Temporales',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: P2, ALA_NORTE)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo (ej: Piso 2, Ala Norte)', max_length=100)),
                ('floor_number', models.IntegerField(blank=True, help_text='Número de piso (para ordenar por proximidad)', null=True)),
                ('priority_order', models.PositiveIntegerField(default=0, help_text='Orden de prioridad para asignación')),
                ('is_active', models.BooleanField(default=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='core.building')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['building', 'floor_number', 'priority_order'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: DEPART, RECOUCH)', max_length=30, unique=True)),
                ('name', models.CharField(help_text='Nombre descriptivo', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('base_minutes', models.PositiveIntegerField(default=30, help_text='Tiempo base en minutos para esta tarea')),
                ('priority', models.PositiveIntegerField(default=50, help_text='Prioridad 1-100 (menor = más prioritario)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_blocks', models.ManyToManyField(help_text='Bloques temporales donde puede realizarse esta tarea', related_name='task_types', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Tipo de Tarea',
                'verbose_name_plural': 'Tipos de Tareas',
                'ordering': ['priority', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='Número de habitación', max_length=20, unique=True)),
                ('order_in_zone', models.PositiveIntegerField(default=0, help_text='Orden dentro de la zona para recorrido eficiente')),
                ('corridor_side', models.CharField(choices=[('A', 'Lado A (Par/Izquierda)'), ('B', 'Lado B (Impar/Derecha)'), ('N', 'No aplica')], default='N', help_text='Lado del pasillo para optimizar recorrido', max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Notas especiales sobre la habitación')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='core.roomtype')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.zone')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['zone', 'order_in_zone', 'number'],
            },
        ),
    ]
