# Generated by Django 4.2.27 on 2026-01-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Hora de fin del bloque (ej: 18:30)', null=True),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Hora de inicio del bloque (ej: 09:00)', null=True),
        ),
    ]
