# Generated by Django 4.2.27 on 2026-01-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_time_to_timeblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='earliest_start_time',
            field=models.TimeField(blank=True, help_text='Hora más temprana para esta tarea (ej: 19:00 para couverture)', null=True),
        ),
        migrations.AddField(
            model_name='tasktype',
            name='latest_end_time',
            field=models.TimeField(blank=True, help_text='Hora límite para terminar (ej: 18:30 para depart/recouch)', null=True),
        ),
    ]
