# Generated by Django 4.2.27 on 2026-01-10 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_task_time_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='persons_required',
            field=models.PositiveIntegerField(default=1, help_text='Personas necesarias para completar en base_minutes (ej: 2 para DEPART)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='base_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo en minutos para completar la tarea (con el número de personas indicado)'),
        ),
    ]
