# Generated by Django 4.2.27 on 2026-01-10 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_persons_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeblock',
            name='helps_other_shift_hours',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Horas que ayuda con tareas del turno DAY (ej: 4.5 para EVENING)', max_digits=3),
        ),
        migrations.AddField(
            model_name='timeblock',
            name='min_staff',
            field=models.PositiveIntegerField(default=2, help_text='Mínimo de personas por turno (ej: 2 para trabajo en parejas)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
