# Generated by Django 4.2.27 on 2026-01-11 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_shift_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktype',
            name='solo_minutes',
            field=models.PositiveIntegerField(default=45, help_text='Tiempo en minutos con 1 PERSONA SOLA. Ej: DEPART=75min, RECOUCH=30min'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='base_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Tiempo en minutos con PAREJA (2 personas). Ej: DEPART=50min, RECOUCH=20min'),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='persons_required',
            field=models.PositiveIntegerField(default=2, help_text='Personas óptimas para la tarea (ej: 2 para DEPART/RECOUCH, 1 para COUVERTURE)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
