# Generated by Django 4.2.27 on 2026-01-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código único (ej: HK_DAY, HK_EVENING, EQ_NIGHT)', max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField(help_text='Hora de inicio')),
                ('end_time', models.TimeField(help_text='Hora de fin')),
                ('break_start', models.TimeField(blank=True, help_text='Inicio de pausa principal', null=True)),
                ('break_end', models.TimeField(blank=True, help_text='Fin de pausa principal', null=True)),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Duración de pausa en minutos')),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='staff.role')),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Plantilla de Turno',
                'verbose_name_plural': 'Plantillas de Turno',
                'ordering': ['role', 'time_block__order'],
                'unique_together': {('role', 'time_block')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSubBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Código del sub-bloque (ej: STANDARD, COUVERTURE, BREAK)', max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False, help_text='¿Es un bloque de descanso?')),
                ('order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, help_text='Descripción de las tareas típicas en este sub-bloque')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_blocks', to='shifts.shifttemplate')),
            ],
            options={
                'verbose_name': 'Sub-bloque de Turno',
                'verbose_name_plural': 'Sub-bloques de Turno',
                'ordering': ['shift_template', 'order', 'start_time'],
            },
        ),
    ]
