# Generated by Django 4.2.27 on 2026-01-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shifttemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='max_daily_hours',
            field=models.PositiveIntegerField(default=8, help_text='Máximo de horas por día'),
        ),
        migrations.AddField(
            model_name='shifttemplate',
            name='weekly_hours_target',
            field=models.PositiveIntegerField(default=39, help_text='Horas semanales objetivo para este turno'),
        ),
    ]
