# Generated by Django 4.2.27 on 2026-01-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('rooms', '0001_initial'),
        ('shifts', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('ACTIVE', 'Activo'), ('COMPLETED', 'Completado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Plan Diario',
                'verbose_name_plural': 'Planes Diarios',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WeekPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start_date', models.DateField(help_text='Fecha del lunes de la semana')),
                ('name', models.CharField(blank=True, help_text="Nombre opcional (ej: 'Semana 3 - Enero')", max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el plan semanal')),
            ],
            options={
                'verbose_name': 'Plan Semanal',
                'verbose_name_plural': 'Planes Semanales',
                'ordering': ['-week_start_date'],
                'unique_together': {('week_start_date',)},
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_in_assignment', models.PositiveIntegerField(default=0, help_text='Orden de la tarea para este empleado/equipo')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En progreso'), ('COMPLETED', 'Completada'), ('SKIPPED', 'Omitida')], default='PENDING', max_length=20)),
                ('started_at', models.TimeField(blank=True, null=True)),
                ('completed_at', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='planning.dailyplan')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='staff.employee')),
                ('room_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='rooms.roomdailytask')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='staff.team')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_assignments', to='core.zone')),
            ],
            options={
                'verbose_name': 'Asignación de Tarea',
                'verbose_name_plural': 'Asignaciones de Tareas',
                'ordering': ['zone', 'order_in_assignment'],
            },
        ),
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Fecha específica')),
                ('assigned_hours', models.DecimalField(decimal_places=2, help_text='Horas asignadas (puede ajustarse del template)', max_digits=4)),
                ('is_day_off', models.BooleanField(default=False, help_text='Marcar si es día libre')),
                ('notes', models.TextField(blank=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='staff.employee')),
                ('shift_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='shifts.shifttemplate')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='staff.team')),
                ('week_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='planning.weekplan')),
            ],
            options={
                'verbose_name': 'Asignación de Turno',
                'verbose_name_plural': 'Asignaciones de Turno',
                'ordering': ['date', 'shift_template__time_block__order'],
            },
        ),
        migrations.CreateModel(
            name='PlanningAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('alert_type', models.CharField(choices=[('OVERLOAD', 'Sobrecarga'), ('UNDERSTAFF', 'Falta personal'), ('CONFLICT', 'Conflicto de asignación'), ('WARNING', 'Advertencia'), ('INFO', 'Información')], default='WARNING', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Alerta de Planificación',
                'verbose_name_plural': 'Alertas de Planificación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='week_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_plans', to='planning.weekplan'),
        ),
        migrations.CreateModel(
            name='DailyLoadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('total_minutes_required', models.PositiveIntegerField(default=0)),
                ('total_employees', models.PositiveIntegerField(default=0)),
                ('total_minutes_available', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('time_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_summaries', to='core.timeblock')),
            ],
            options={
                'verbose_name': 'Resumen de Carga Diaria',
                'verbose_name_plural': 'Resúmenes de Carga Diaria',
                'ordering': ['date', 'time_block__order'],
                'unique_together': {('date', 'time_block')},
            },
        ),
    ]
