# Generated by Django 4.2.27 on 2026-01-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekplan',
            name='forecast_data',
            field=models.JSONField(blank=True, help_text='Datos del forecast: departures, arrivals, occupied por día', null=True),
        ),
        migrations.AddField(
            model_name='weekplan',
            name='load_calculation',
            field=models.JSONField(blank=True, help_text='Cálculo de carga: horas por turno, personas necesarias', null=True),
        ),
    ]
